import React from 'react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent } from '@testing-library/react'
import { NextIntlClientProvider } from 'next-intl'
import ErrorDisplay from '../ErrorDisplay'

const messages = {
  'markdown-import': {
    errorDetails: {
      networkError: {
        title: 'Connection Problem',
        message: 'Unable to connect to the server'
      },
      validationError: {
        title: 'Invalid File',
        message: 'The selected file is not valid'
      },
      processingError: {
        title: 'Processing Failed',
        message: 'Failed to process the Markdown content'
      },
      serverError: {
        title: 'Server Error',
        message: 'The server encountered an error'
      },
      fileSystemError: {
        title: 'File System Error',
        message: 'Unable to save the file'
      },
      unknownError: {
        title: 'Unexpected Error',
        message: 'An unexpected error occurred'
      }
    }
  }
}

const renderWithIntl = (component: React.ReactElement) => {
  return render(
    <NextIntlClientProvider locale="en" messages={messages}>
      {component}
    </NextIntlClientProvider>
  )
}

describe('ErrorDisplay', () => {
  const mockOnRetry = vi.fn()
  const mockOnDismiss = vi.fn()

  beforeEach(() => {
    vi.clearAllMocks()
  })

  it('should render network error correctly', () => {
    const error = new Error('fetch failed: network error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onRetry={mockOnRetry} 
        onDismiss={mockOnDismiss} 
      />
    )

    expect(screen.getByText('Connection Problem')).toBeInTheDocument()
    expect(screen.getByText('Unable to connect to the server')).toBeInTheDocument()
  })

  it('should render validation error correctly', () => {
    const error = new Error('Invalid file type: .txt not allowed')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onRetry={mockOnRetry} 
        onDismiss={mockOnDismiss} 
      />
    )

    expect(screen.getByText('Invalid File')).toBeInTheDocument()
    expect(screen.getByText('The selected file is not valid')).toBeInTheDocument()
  })

  it('should show retry button for retryable errors', () => {
    const error = new Error('network error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onRetry={mockOnRetry} 
        onDismiss={mockOnDismiss} 
      />
    )

    const retryButton = screen.getByText('Try Again')
    expect(retryButton).toBeInTheDocument()

    fireEvent.click(retryButton)
    expect(mockOnRetry).toHaveBeenCalledTimes(1)
  })

  it('should not show retry button for non-retryable errors', () => {
    const error = new Error('Invalid file type')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onRetry={mockOnRetry} 
        onDismiss={mockOnDismiss} 
      />
    )

    expect(screen.queryByText('Try Again')).not.toBeInTheDocument()
  })

  it('should show dismiss button when onDismiss is provided', () => {
    const error = new Error('Some error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onDismiss={mockOnDismiss} 
      />
    )

    const dismissButton = screen.getByText('Dismiss')
    expect(dismissButton).toBeInTheDocument()

    fireEvent.click(dismissButton)
    expect(mockOnDismiss).toHaveBeenCalledTimes(1)
  })

  it('should show/hide technical details', () => {
    const error = new Error('Detailed error message')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onDismiss={mockOnDismiss} 
      />
    )

    // Initially details should be hidden
    expect(screen.queryByText('Detailed error message')).not.toBeInTheDocument()

    // Click to show details
    const showDetailsButton = screen.getByText('Show Technical Details')
    fireEvent.click(showDetailsButton)

    expect(screen.getByText('Detailed error message')).toBeInTheDocument()
    expect(screen.getByText('Hide Technical Details')).toBeInTheDocument()

    // Click to hide details
    const hideDetailsButton = screen.getByText('Hide Technical Details')
    fireEvent.click(hideDetailsButton)

    expect(screen.queryByText('Detailed error message')).not.toBeInTheDocument()
    expect(screen.getByText('Show Technical Details')).toBeInTheDocument()
  })

  it('should display error suggestions', () => {
    const error = new Error('network error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onDismiss={mockOnDismiss} 
      />
    )

    expect(screen.getByText('Suggestions:')).toBeInTheDocument()
    // The suggestions are generated by ErrorHandler, so we just check that the section exists
  })

  it('should handle errors without onRetry callback', () => {
    const error = new Error('network error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onDismiss={mockOnDismiss} 
      />
    )

    // Should not show retry button when onRetry is not provided
    expect(screen.queryByText('Try Again')).not.toBeInTheDocument()
  })

  it('should handle errors without onDismiss callback', () => {
    const error = new Error('network error')

    renderWithIntl(
      <ErrorDisplay 
        error={error} 
        onRetry={mockOnRetry} 
      />
    )

    // Should not show dismiss button when onDismiss is not provided
    expect(screen.queryByText('Dismiss')).not.toBeInTheDocument()
  })

  it('should apply custom className', () => {
    const error = new Error('test error')

    const { container } = renderWithIntl(
      <ErrorDisplay 
        error={error} 
        className="custom-class" 
      />
    )

    expect(container.firstChild).toHaveClass('custom-class')
  })
})