import React from 'react';
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import MarkdownPreview from '../MarkdownPreview';

/**
 * Integration tests for MarkdownPreview with real markdown processing
 * These tests use the actual remark libraries without mocking
 */
describe('MarkdownPreview Integration Tests', () => {
  it('processes real markdown content correctly', async () => {
    const markdownContent = `# Test Heading

This is a **bold** text and *italic* text.

- Item 1
- Item 2

\`inline code\`
`;

    render(<MarkdownPreview content={markdownContent} />);
    
    // Wait for processing and check that content is rendered
    const contentDiv = document.querySelector('.prose');
    expect(contentDiv).toBeInTheDocument();
    
    // The actual HTML structure will be generated by remark
    expect(contentDiv?.innerHTML).toBeTruthy();
  });

  it('handles empty content gracefully', () => {
    render(<MarkdownPreview content="" />);
    
    expect(screen.getByText('No content to preview')).toBeInTheDocument();
  });

  it('applies correct CSS classes', () => {
    render(<MarkdownPreview content="# Test" />);
    
    const wrapper = document.querySelector('.markdown-preview');
    expect(wrapper).toBeInTheDocument();
    
    const prose = document.querySelector('.prose');
    expect(prose).toHaveClass('prose', 'prose-lg', 'max-w-none');
  });

  it('shows original content when requested', () => {
    const content = "# Test\n\nContent";
    render(<MarkdownPreview content={content} showOriginal={true} />);
    
    expect(screen.getByText('Original Markdown:')).toBeInTheDocument();
    
    const preElement = document.querySelector('pre');
    expect(preElement?.textContent?.trim()).toBe(content);
  });
});